#!/usr/bin/env python

import sys, getopt
from PIL import Image

palette = {(63, 63, 63): 0,  #background
        (0, 0, 0): 1,        #wall
        (40, 40, 40): 2,     #shootable wall
        (0, 0, 63): 3}       #portal

def main(argv):
   inputfile = ''
   outputfile = ''

   # HANDLE FLAGS
   # -h: print command format
   # -i: name of png file that need to be converted
   # -o: name of the output binary file that you want to create
   try:
      opts, args = getopt.getopt(argv,"hi:o:",["ifile=","ofile="])
   except getopt.GetoptError:
      print('USAGE:\n\tconverter -i <inputfile> -o <outputfile>')
      sys.exit(2)
   for opt, arg in opts:
      if opt == '-h':
         print('converter -i <inputfile> -o <outputfile>')
         sys.exit()
      elif opt in ("-i", "--input"):
         inputfile = arg
      elif opt in ("-o", "--output"):
         outputfile = arg

   # CODE TO GENERATE BINAIRY
   img_png = Image.open(inputfile) 
   pixels = img_png.load()  # load image in to an array of pixels
   width, height = img_png.size

   with open(outputfile, 'wb') as output: # Convert pixels one by one to corresponding binairy in the palette
        output.write(height.to_bytes(2, 'little')) # write height to file
        output.write(width.to_bytes(2, 'little'))  # write width to file
        for h in range(height):
            for w in range(width):
                r, g, b = map(lambda n : n >> 2, pixels[w, h]) # shift pixel color from 8bit to 6bit color
                byte = (palette[(r, g, b)]).to_bytes(1, 'little') # get corresponding palette binary value
                output.write(byte) # write binary to file

if __name__ == "__main__":
   main(sys.argv[1:])
